from contextlib import contextmanager
from pathlib import Path
import os
import sqlite3

from flask import Flask, abort, jsonify, request, send_from_directory

BASE_DIR = Path(__file__).resolve().parent
DB_PATH = Path(os.environ.get("DATABASE_PATH", str(BASE_DIR / "cafe.db")))
DATABASE_URL = os.environ.get("DATABASE_URL", "").strip()

app = Flask(__name__, static_folder=None)


@contextmanager
def db_connection():
    if DATABASE_URL:
        import psycopg

        # 接続失敗時にSQLiteへ切り替えない。URLはログに出力しない。
        try:
            conn = psycopg.connect(DATABASE_URL, connect_timeout=10)
        except psycopg.Error:
            raise RuntimeError("PostgreSQLへの接続に失敗しました。RenderのDB設定を確認してください。") from None
    else:
        DB_PATH.parent.mkdir(parents=True, exist_ok=True)
        conn = sqlite3.connect(DB_PATH)

    try:
        yield conn
        conn.commit()
    except Exception:
        conn.rollback()
        raise
    finally:
        conn.close()


def init_db():
    id_column = (
        "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
        if DATABASE_URL else "INTEGER PRIMARY KEY AUTOINCREMENT"
    )

    with db_connection() as conn:
        conn.execute(f"""
            CREATE TABLE IF NOT EXISTS contacts (
                id {id_column},
                name TEXT,
                message TEXT
            )
        """)


init_db()


@app.route("/")
def home():
    return send_from_directory(BASE_DIR, "index.html")


@app.route("/api/contact", methods=["POST"])
def contact():
    data = request.get_json(silent=True)

    if not isinstance(data, dict):
        return jsonify(
            status="error",
            message="JSON形式で送信してください。"
        ), 400

    name = data.get("name")
    message = data.get("message")

    if not isinstance(name, str) or not isinstance(message, str):
        return jsonify(
            status="error",
            message="名前とお問い合わせ内容を文字列で送信してください。"
        ), 400

    placeholders = "%s, %s" if DATABASE_URL else "?, ?"
    with db_connection() as conn:
        conn.execute(
            f"INSERT INTO contacts (name, message) VALUES ({placeholders})",
            (name, message)
        )

    return jsonify({
        "status": "success",
        "message": f"{name}さん、お問い合わせを保存しました！"
    })


@app.route("/api/contacts", methods=["GET"])
def get_contacts():
    with db_connection() as conn:
        contacts = conn.execute(
            "SELECT id, name, message FROM contacts ORDER BY id"
        ).fetchall()

    return jsonify(contacts)


@app.route("/<path:filename>")
def files(filename):
    if filename not in {"index.html", "style.css", "script.js"}:
        abort(404)

    return send_from_directory(BASE_DIR, filename)


if __name__ == "__main__":
    app.run(debug=os.environ.get("FLASK_DEBUG") == "1")
