"""一時SQLiteとPostgreSQL接続の代役で検証。本番DBには接続しない。"""
import importlib.util
import os
from pathlib import Path
import sqlite3
import tempfile
import unittest
from unittest.mock import MagicMock, patch

import psycopg


def load_server():
    spec = importlib.util.spec_from_file_location("tested_server", Path(__file__).with_name("server.py"))
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    module.app.config["TESTING"] = True
    return module


class SQLiteTests(unittest.TestCase):
    def setUp(self):
        self.temp = tempfile.TemporaryDirectory()
        self.addCleanup(self.temp.cleanup)
        self.db = Path(self.temp.name) / "nested" / "test.db"
        env = patch.dict(os.environ, {"DATABASE_URL": "", "DATABASE_PATH": str(self.db)})
        env.start()
        self.addCleanup(env.stop)
        self.server = load_server()
        self.client = self.server.app.test_client()

    def test_save_list_restart_and_existing_data(self):
        self.assertEqual(self.client.get("/api/contacts").json, [])
        name, message = "太郎 O'Reilly", "こんにちは'); DROP TABLE contacts; --"
        response = self.client.post("/api/contact", json={"name": name, "message": message})
        self.assertEqual(response.status_code, 200)
        self.assertEqual(response.json["status"], "success")
        restarted = load_server().app.test_client()
        self.assertEqual(restarted.get("/api/contacts").json, [[1, name, message]])
        restarted.post("/api/contact", json={"name": "二郎", "message": "2件目"})
        self.assertEqual([r[0] for r in restarted.get("/api/contacts").json], [1, 2])

    def test_invalid_input_and_private_files(self):
        for payload in [None, [], {}, {"name": 42, "message": "text"}]:
            self.assertEqual(self.client.post("/api/contact", json=payload).status_code, 400)
        self.assertEqual(self.client.post("/api/contact", data="{", content_type="application/json").status_code, 400)
        for filename in ["server.py", "cafe.db", ".env", "requirements.txt", "test_server.py"]:
            self.assertEqual(self.client.get("/" + filename).status_code, 404)
        self.assertEqual(self.client.get("/api/contacts").json, [])

    def test_rollback_and_close(self):
        with self.assertRaisesRegex(ValueError, "test failure"):
            with self.server.db_connection() as conn:
                conn.execute("INSERT INTO contacts (name, message) VALUES (?, ?)", ("rollback", "test"))
                raise ValueError("test failure")
        self.assertEqual(self.client.get("/api/contacts").json, [])
        with self.assertRaises(sqlite3.ProgrammingError):
            conn.execute("SELECT 1")


class PostgreSQLRoutingTests(unittest.TestCase):
    def test_postgresql_init_insert_select_and_cleanup(self):
        # このURLはテスト用。connectを置換するため通信しない。
        with tempfile.TemporaryDirectory() as temp, patch.dict(os.environ, {
            "DATABASE_URL": "postgresql://test.invalid/test",
            "DATABASE_PATH": str(Path(temp) / "must-not-exist.db"),
        }), patch.object(psycopg, "connect") as connect, patch.object(sqlite3, "connect") as sqlite_connect:
            conn = connect.return_value
            module = load_server()
            ddl = conn.execute.call_args.args[0]
            self.assertIn("GENERATED BY DEFAULT AS IDENTITY", ddl)
            self.assertNotIn("AUTOINCREMENT", ddl)
            conn.commit.assert_called_once()
            conn.close.assert_called_once()
            connect.assert_called_once_with(module.DATABASE_URL, connect_timeout=10)
            conn.reset_mock()
            client = module.app.test_client()
            self.assertEqual(client.post("/api/contact", json={"name": "O'Reilly", "message": "日本語"}).status_code, 200)
            conn.execute.assert_called_once_with("INSERT INTO contacts (name, message) VALUES (%s, %s)", ("O'Reilly", "日本語"))
            conn.commit.assert_called_once()
            conn.close.assert_called_once()
            conn.reset_mock()
            conn.execute.return_value.fetchall.return_value = [(1, "O'Reilly", "日本語")]
            self.assertEqual(client.get("/api/contacts").json, [[1, "O'Reilly", "日本語"]])
            conn.execute.assert_called_once_with("SELECT id, name, message FROM contacts ORDER BY id")
            conn.close.assert_called_once()
            conn.reset_mock()
            conn.execute.side_effect = psycopg.DatabaseError("simulated write failure")
            with self.assertRaises(psycopg.DatabaseError):
                client.post("/api/contact", json={"name": "failure", "message": "test"})
            conn.rollback.assert_called_once()
            conn.close.assert_called_once()
            conn.commit.assert_not_called()
            sqlite_connect.assert_not_called()

    def test_connection_failure_does_not_fallback_or_expose_url(self):
        with patch.dict(os.environ, {"DATABASE_URL": "postgresql://test.invalid/test"}), patch.object(
            psycopg, "connect", side_effect=psycopg.OperationalError("sensitive connection details")
        ), patch.object(sqlite3, "connect") as sqlite_connect:
            with self.assertRaises(RuntimeError) as error:
                load_server()
            self.assertNotIn("sensitive", str(error.exception))
            self.assertTrue(error.exception.__suppress_context__)
            sqlite_connect.assert_not_called()


if __name__ == "__main__":
    unittest.main()
